### ISSUE TITLE
does not detect env variable APLAZAME_API_BASE_URI

### ISSUE THREAD

**Issue by jgermade** [aplazame/woocommerce#17]
env variable APLAZAME_API_BASE_URI not detected in http://woo-dev.aplazame.com/

**Comment by Maks3w** [comment]
This plugin rely on constants instead env vars as this is the common way of tune settings on WordPress

https://github.com/aplazame/woocommerce/blob/master/plugin/aplazame.php#L340

It's possible use env vars by adding this to your `wp-config.php`

`define('APLAZAME_API_BASE_URI', gentenv('APLAZAME_API_BASE_URI'));`
