### ISSUE TITLE
WC_Order::get_payment_method() undefined in VERY old versions of Woocommerce

### ISSUE THREAD

**Issue by nachoatwork** [aplazame/woocommerce#38]
The plugin is working in my Woocommerce version 2.6.14 but it shows the following error when "completing" orders: 

PHP Fatal error:  Call to undefined method WC_Order::get_payment_method() in /var/www/html/wp-content/plugins/aplazame/aplazame.php on line 331,

My patch:

```
318,322c318
< 		if (method_exists($order,'get_payment_method')) {
< 			return $order->get_payment_method() === self::METHOD_ID;
< 		} else {
< 			return $order->payment_method === self::METHOD_ID . '_' . self::PAY_LATER;
< 		}
---
> 		return $order->get_payment_method() === self::METHOD_ID;
333,337c329
< 		if (method_exists($order,'get_payment_method')) {
< 			return $order->get_payment_method() === self::METHOD_ID . '_' . self::PAY_LATER;
< 		} else {
< 			return $order->payment_method === self::METHOD_ID . '_' . self::PAY_LATER;
< 		}
---


```

**Comment by alexhernandezord** [comment]
There's a function for this cases: https://github.com/aplazame/woocommerce/blob/master/plugin/aplazame.php#L44-L50

Better use it because "else" in the first function is incorrect, the correct use is:
```
	protected static function is_aplazame_order( $order_id ) {
		$order = wc_get_order( $order_id );
		return self::_m_or_m($order,'get_payment_method', 'payment_method') === self::METHOD_ID;
	}

	protected static function is_aplazame_pay_later_order( $order_id ) {
		$order = wc_get_order( $order_id );
		return self::_m_or_m($order,'get_payment_method', 'payment_method') === self::METHOD_ID . '_' . self::PAY_LATER;
	}
```

We'll fix this in future releases, thanks.

**Comment by nachoatwork** [comment]
Sorry, I didn't notice about the existence of this method. But I think it should be replaced by "_m_or_a", as "payment_method" is an attribute (at least in my very old woocommerce 2.6.14).

Thanks for your reply.

**Comment by alexhernandezord** [comment]
You're right, sorry for the mistake. The correct function is "_m_or_a". We'll prepare a new release with this fix next week.

Thanks for the help.

**Comment by nachoatwork** [comment]
Sorry, same issue in: 
plugin/classes/api/Aplazame_Api_ConfirmController.php
Thanks again.

**Comment by alexhernandezord** [comment]
We'll fix it and deply a new release tomorrow morning.
Thanks again for the help.

**Comment by alexhernandezord** [comment]
Last release with this issue fixed: https://github.com/aplazame/woocommerce/releases/tag/v2.2.2
